#include <stdio.h>

/*
Defina una estructura para que guarde una longitud expresada en
metros, centímetros y milímetros. Luego defina dos variables de este tipo
y tome una longitud desde el teclado. Realice la suma de ambas variables
y muestre el resultado en metros,centímetros.
*/

// GENERATED BY IA

typedef struct
{
  int metros;
  int centimetros;
  int milimetros;
} Longitud;

int main()
{
  // Declarar variables de tipo Longitud
  Longitud longitud1;
  Longitud longitud2;
  Longitud resultado;

  // Tomar una longitud desde el teclado
  printf("Ingrese la longitud 1 (en metros, centimetros y milimetros): ");
  scanf("%d %d %d", &longitud1.metros, &longitud1.centimetros, &longitud1.milimetros);

  printf("Ingrese la longitud 2 (en metros, centimetros y milimetros): ");
  scanf("%d %d %d", &longitud2.metros, &longitud2.centimetros, &longitud2.milimetros);

  // Calcular la suma
  resultado.metros = longitud1.metros + longitud2.metros;
  resultado.centimetros = longitud1.centimetros + longitud2.centimetros;
  resultado.milimetros = longitud1.milimetros + longitud2.milimetros;

  // Ajustar los valores en caso de exceder los límites
  if (resultado.milimetros >= 1000)
  {
    resultado.milimetros -= 1000;
    resultado.centimetros++;
  }

  if (resultado.centimetros >= 100)
  {
    resultado.centimetros -= 100;
    resultado.metros++;
  }

  // Mostrar el resultado
  printf("Resultado de la suma: %d metros, %d centimetros y %d milimetros.\n", resultado.metros, resultado.centimetros, resultado.milimetros);

  return 0;
}
